### ISSUE TITLE
the main process exits unexpectedly

### ISSUE THREAD

**Issue by baiyies** [aaaddress1/RunPE-In-Memory#15]
Hello, this is a awesome project. I find a problem when I load the `32bit.exe` test file, it works, however when the 32bit.exe ends normally, the main process exits too, is it possible to create a new process to load the pe file? Or any ways to let the main process continue to execute?

**Comment by aaaddress1** [comment]
sure, you can check out my another project to do it.

https://github.com/aaaddress1/PR0CESS/tree/main/miniCreateProcessEx

but I suggest you make a API hijacking on ExitProcess() for simple :)
