### ISSUE TITLE
如何传入目标exe参数？

### ISSUE THREAD

**Issue by liuzy88** [aaaddress1/RunPE-In-Memory#3]
??
RunPEinMemory.exe my.exe p1 p2

**Comment by aaaddress1** [comment]
Hi 這邊實作的是一個 Application Loader 程序裝載器的概念。執行程序參數可以透過逆向工程的方式分析得知會以 Win32 API 如 GetCommandLine() 去抓取。沒記錯，這一段參數資訊會放置於 PEB 內實作，您可以寫另一塊模組去修改 PEB 參數資訊或者對自身 GetCommandLine() 函數上 patch 亦可。
