### ISSUE TITLE
导入表重定向存在问题

### ISSUE THREAD

**Issue by Lz1y** [aaaddress1/RunPE-In-Memory#4]
尝试把mimikatz pack，但是发现总是没办法运行。。。调试了一下发现只加载了第一个dll
![](https://raw.githubusercontent.com/Lz1y/imggo/master/20190502002212.png)

**Comment by Lz1y** [comment]
顺便说一下，好项目！

**Comment by Lz1y** [comment]
加上通过序号名查找函数地址的支持就行啦
![](https://raw.githubusercontent.com/Lz1y/imggo/master/20190502012518.png)

**Comment by aaaddress1** [comment]
感謝支持，如果可以的話您可以把改動後的作法提交上來，感謝！
