### ISSUE TITLE
Pass Another Process as Argument 

### ISSUE THREAD

**Issue by Testcase4** [aaaddress1/RunPE-In-Memory#7]
I could not understand that how to pass another process as argument ( To which Payload process will replace )

Forexample
peLoader( OriginalexePath , PayloadexePath)

Could you please help me in understanding the same?

**Comment by aaaddress1** [comment]
that's kinda dirty work I don't wanna add this into my project :/ 

after a little bit reversing into KernelBase!GetCommandLineW you will see the following code inside KernelBaseBaseDllInitialize:

![image](https://user-images.githubusercontent.com/8559056/90557592-4cb99f00-e1cd-11ea-8a8b-56f0a3f0ac41.png)

there's a global buffer named BaseUnicodCommandLine.Buffer (UnicodeString) will be filled in current commandline string from PEB→ProcessParmetersCommandLine, like that "C:\a.exe" arg1 arg2. so there's 2 options for you to choose: 

(a.) search the pointer of BaseUnicodCommandLine in your memory and replace it to you want by ntdll!RutlUnicodeString() 

(b.) make a function hook to patch the return string by GetCommandLineA/W (better and easier)

---
you will found that arguments from `main(argc, argv)` won't change if you have do (a.) or (b.). after do resversing on msvcrt.dll like the following code:

![image](https://user-images.githubusercontent.com/8559056/90558242-51328780-e1ce-11ea-95c8-2751666d9227.png)

you will find that there's another global buffer to cache commandline string when msvcrt.dll is loaded. so a better idea is: first, hook GetCommandLineA/W to return what you want. second, free the msvcrt module from your memory. and third, load msvcrt module again (to refresh that cache)

**Comment by Testcase4** [comment]
Hi ,
Thank you for response :)
I want to know why it is dirty work? 
Is it not preferable because AV catches it ?
Also you have explained me how to do it but It is quite bypassing my memory to understand this :(

**Comment by aaaddress1** [comment]
hi there.

ugh just like some work you can do it in C, you won't wanna do it in assembly that kinda dirty work. if you're still interested, you can take a look about my another project for hooking `CreateProcess()`: https://github.com/aaaddress1/Dad-sRoot/blob/master/GobalDLL/Hook_CreateProcess.h

**Comment by Testcase4** [comment]
Hi here :)

Ok, I will go through it. I have one more question and what is the difference between the two 
https://github.com/aaaddress1/RunPE-In-Memory/blob/master/runPE/runPE/runPE.cpp
https://github.com/aaaddress1/RunPE-In-Memory/blob/master/RunPE-In-Memory/RunPEinMemory/RunPEinMemory.cpp

**Comment by aaaddress1** [comment]
hey check out my slide for this project: https://speakerdeck.com/aaaddress1/implementing-software-packer-at-vxcon?slide=39

**Comment by Testcase4** [comment]
Hi,
Thanks for sharing the ppt.
Please check your mailbox : aaaddress1@chroot.org

**Comment by Testcase4** [comment]
> that's kinda dirty work I don't wanna add this into my project :/
> 
> after a little bit reversing into KernelBase!GetCommandLineW you will see the following code inside KernelBaseBaseDllInitialize:
> 
> ![image](https://user-images.githubusercontent.com/8559056/90557592-4cb99f00-e1cd-11ea-8a8b-56f0a3f0ac41.png)
> 
> there's a global buffer named BaseUnicodCommandLine.Buffer (UnicodeString) will be filled in current commandline string from PEB→ProcessParmetersCommandLine, like that "C:\a.exe" arg1 arg2. so there's 2 options for you to choose:
> 
> (a.) search the pointer of BaseUnicodCommandLine in your memory and replace it to you want by ntdll!RutlUnicodeString()
> 
> (b.) make a function hook to patch the return string by GetCommandLineA/W (better and easier)
> 
> you will found that arguments from `main(argc, argv)` won't change if you have do (a.) or (b.). after do resversing on msvcrt.dll like the following code:
> 
> ![image](https://user-images.githubusercontent.com/8559056/90558242-51328780-e1ce-11ea-95c8-2751666d9227.png)
> 
> you will find that there's another global buffer to cache commandline string when msvcrt.dll is loaded. so a better idea is: first, hook GetCommandLineA/W to return what you want. second, free the msvcrt module from your memory. and third, load msvcrt module again (to refresh that cache)

Hi
Could you please let me know that Are you able to see all these details using Visual Studio 2017 because I can not see this deep detail there ? 
Also which platform are you using to see this much detail ?

**Comment by aaaddress1** [comment]
Hey check out new feature: https://github.com/aaaddress1/RunPE-In-Memory/commit/44b860821e46d2f64d2d16d939c73b337edcec58. I've added new feature to support control arguments.
