### ISSUE TITLE
最新win10x64下载入notepad.exe报0地址异常。

### ISSUE THREAD

**Issue by xiaoyao66** [aaaddress1/RunPE-In-Memory#9]
x86 debug版本和 x64 debug版本都报0地址异常，无法执行。是不是不支持win10？

**Comment by aaaddress1** [comment]
hey 可以的話確定一下 notepad.exe (64bit) prefer 的 image base 是否已經被佔用, 
若是則會導致 VirtualAlloc() 失效返回 0 基址
